# Generated by Django 3.2.4 on 2021-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=300)),
                ('extension', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('length', models.FloatField()),
                ('record_type', models.CharField(max_length=10)),
            ],
        ),
    ]
